name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Eunomo (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    strategy:
      matrix:
        include:
          - otp: "25.x"
            elixir: "1.13.4"
          - otp: "25.x"
            elixir: "1.14.5"
          - otp: "26.x"
            elixir: "1.15.7"
          - otp: "26.x"
            elixir: "1.16.2"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache mix dependencies
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile App
        run: mix compile

      - name: Run formatter
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Run Docs
        run: mix docs

      - name: Run Tests
        run: mix test

      - name: Run dialyzer
        run: mix dialyzer
