name: CI
on: [pull_request, push]
jobs:
  test:
    name: Eunomo (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    strategy:
      matrix:
        elixir: ['1.10.0', '1.10.1', '1.10.2']
        include:
          - elixir: '1.10.0'
            otp: '22.x'
          - elixir: '1.10.1'
            otp: '22.x'
          - elixir: '1.10.2'
            otp: '22.x'
    runs-on: ubuntu-16.04
    steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-elixir@v1
          with:
            otp-version: ${{ matrix.otp }}
            elixir-version: ${{ matrix.elixir }}

        - name: Cache mix dependencies
          uses: actions/cache@v1
          with:
            path: deps
            key: ${{ runner.os }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
            restore-keys: ${{ runner.os }}-mix-

        - name: Cache dialyzer plt
          uses: actions/cache@v1
          with:
            path: plts
            key: ${{ runner.os }}-${{ matrix.elixir }}-dialyzer
            restore-keys: ${{ runner.os }}-${{ matrix.elixir }}-dialyzer

        - name: Install Dependencies
          run: mix deps.get

        - name: Run formatter
          run: mix format --check-formatted

        - name: Run Eunomo
          run: mix eunomo --check-formatted

        - name: Run Credo
          run: mix credo --strict

        - name: Run Tests
          run: mix test

        - name: Run dialyzer
          run: mkdir -p plts && mix dialyzer --halt-exit-status