name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Eunomo (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    strategy:
      matrix:
        include:
          - otp: "22.x"
            elixir: "1.13.4"
          - otp: "25.x"
            elixir: "1.13.4"
          - otp: "23.x"
            elixir: "1.14.1"
          - otp: "25.x"
            elixir: "1.14.1"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache mix dependencies
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Run formatter
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Run Docs
        run: mix docs

      - name: Run Tests
        run: mix test_all

      - name: Run dialyzer
        run: mix dialyzer
